### ISSUE TITLE
Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by Antweerp** [morassman/tabasco#1]
`Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Antweerp/.atom/packages/tabasco/lib/tabasco.coffee:2:7)
    at Object.<anonymous> (/Users/Antweerp/.atom/packages/tabasco/lib/tabasco.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)`

Hey ! I've just installed the package, had this error when launching Atom.

**Comment by morassman** [comment]
Hi

tabasco depends on atom-space-pen-views and it should get automatically installed along with it. Maybe something went wrong during the install that wasn't reported. I know it's a bit lame, but try to uninstall and re-install tabasco.

If that doesn't work. Please let me know what version of Atom you're running and what OS you're using so that I can try and reproduce the issue.

**Comment by morassman** [comment]
Are you still experiencing this problem? v0.4.0 was just released. Install it and let me know if you're still getting this problem. If something did go wrong with the previous installation then maybe first uninstall it instead of upgrading.
