### ISSUE TITLE
Exception creating new pane with About tab: "The workspace can only contain one instance of item"

### ISSUE THREAD

**Issue by infogulch** [morassman/tabasco#5]
I'll admit this one is a bit obscure. Repro:
1. Open the "About" page. (Help menu > About Atom)
2. Drag and drop the About tab to an edge to create a new pane with it.
3. The exception below is thrown.

Note: this only occurs when creating a _new_ pane with the About tab, not moving the About tab between existing panes.

I would guess that it's trying to clone the tab before removing the existing tab. But the Settings tab has the same property and it doesn't produce this problem.

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [tabasco](https://github.com/morassman/tabasco) package, v0.4.1
### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane-container.js:387:25)
    at C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane-container.js:366:19
    at C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane-container.js:97:16
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane-container.js:306:27)
    at Pane.module.exports.Pane.setContainer (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane.js:125:26)
    at PaneAxis.module.exports.PaneAxis.addChild (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane-axis.js:144:13)
    at PaneAxis.module.exports.PaneAxis.insertChildBefore (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane-axis.js:210:19)
    at Pane.module.exports.Pane.split (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane.js:892:23)
    at Pane.module.exports.Pane.splitLeft (C:\Users\%username%\AppData\Local\atom\app-1.7.2\resources\app.asar\src\pane.js:852:19)
    at tabasco-zone.module.exports.TabascoZone.moveItemToTarget (file:///C:/Users/%username%/.atom/packages/tabasco/lib/tabasco-zone.coffee:96:29)
    at tabasco-zone.module.exports.TabascoZone.handleDrop (file:///C:/Users/%username%/.atom/packages/tabasco/lib/tabasco-zone.coffee:78:6)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
atom-yeoman, v0.3.15
autocomplete-go, v1.0.6
builder-go, v1.0.0
editorconfig, v1.3.0
environment, v1.2.0
go-config, v1.1.4
go-debug, v0.1.7
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
json-schema, v0.1.15
language-powershell, v2.1.1
language-sln, v0.1.0
linter, v1.11.4
minimap, v4.22.1
navigator-godef, v1.0.3
omnisharp-atom, v0.28.0
open_in_cmd, v0.6.1
pretty-json, v1.0.3
sync-settings, v0.7.2
tabasco, v0.4.1
tester-go, v1.0.4
vim-mode, v0.65.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by morassman** [comment]
Hmmm. This is rather obscure. I'll have to debug a bit.

**Comment by morassman** [comment]
This turned out to be due to [another](https://github.com/atom/tabs/issues/234) bug. One can actually reproduce it without tabasco even installed by splitting the About pane manually.

It was reported last year already, but I personally think that the bug is lower down in Atom and not in the tabs package. Both tabs and tabasco use the same API to split panes. A [similar](https://github.com/atom/atom/issues/7307) bug with the same stack trace has also already been logged on Atom itself.

**Comment by infogulch** [comment]
Oh I see. Thanks for the update. :+1:
