### ISSUE TITLE
Seems to be broken with Atom v1.11

### ISSUE THREAD

**Issue by lierdakil** [morassman/tabasco#7]
[Enter steps to reproduce below:]
1. Create two editor tabs
2. Try to dock one tab to the left

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: "Gentoo Base
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.101.0
### Stack Trace

Uncaught Error: Adding a pane item with URI 'undefined' that has already been destroyed

```
At /home/livid/atom/out/app/src/pane.coffee:459

Error: Adding a pane item with URI 'undefined' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/home/livid/atom/out/atom-1.11.2-amd64/resources/app.asar/src/pane.js:459:15)
    at Pane.module.exports.Pane.moveItemToPane (/home/livid/atom/out/atom-1.11.2-amd64/resources/app.asar/src/pane.js:616:19)
    at Object.module.exports.end (/home/livid/atom/out/atom-1.11.2-amd64/resources/app.asar/node_modules/tabs/lib/layout.js:60:16)
    at tabs-tab.ondragend (/home/livid/atom/out/atom-1.11.2-amd64/resources/app.asar/node_modules/tabs/lib/tab-view.js:54:23)
```
### Commands

```
     -0:08.8.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:08.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:07.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.7.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:06.1.0 application:new-file (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "atom-lint",
      "haskell-hindent",
      "autocomplete",
      "linter-hlint",
      "markdown-preview",
      "tabs-to-spaces",
      "hunspell-linter",
      "inline-markdown-images",
      "linter-php"
    ],
    "packagesWithKeymapsDisabled": [
      "build"
    ],
    "telemetryConsent": "limited"
  },
  "tabs": {}
}
```
### Installed Packages

``` coffee
# User
atom-terminal, v0.8.0 (inactive)
autocomplete-clang, v0.10.0 (active)
autocomplete-cmake, v0.3.1 (active)
autocomplete-haskell, v0.6.7 (active)
autocomplete-mathjax, v0.1.1 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-python, v1.8.6 (active)
build, v0.65.0 (active)
build-cmake, v0.6.4 (active)
build-make, v0.13.0 (active)
build-npm-apm, v0.12.0 (active)
busy, v0.7.0 (active)
csslint, v1.1.5 (active)
date, v1.1.1 (inactive)
git-plus, v5.18.0 (active)
haskell-ghc-mod, v1.19.0 (active)
haskell-pointfree, v0.1.3 (active)
ide-haskell, v1.8.2 (active)
ide-haskell-cabal, v1.6.4 (active)
ide-haskell-hasktags, v0.0.7 (active)
ide-haskell-hoogle, v0.0.0 (active)
ide-haskell-profiteurjs, v0.0.2 (active)
ide-haskell-repl, v0.3.1 (active)
ide-haskell-settings, v0.0.0 (active)
inline-markdown-images, v1.0.0 (inactive)
language-cmake, v0.2.0 (active)
language-dot, v1.6.0 (active)
language-haskell, v1.9.12 (active)
language-haskell-scoped, v0.0.3 (active)
language-latex, v1.0.0 (active)
language-pfm, v0.82.0 (active)
latex, v0.38.1 (inactive)
latex-autocomplete, v1.0.0 (active)
linter, v1.11.18 (active)
linter-coffeelint, v1.1.2 (active)
linter-eslint, v8.0.0 (active)
linter-hlint, v0.5.0 (inactive)
linter-less, v2.6.0 (active)
linter-php, v1.3.1 (inactive)
linter-pylint, v1.2.2 (active)
markdown-folder, v0.5.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
markdown-table-formatter, v2.8.3 (active)
markdown-writer, v2.6.1 (inactive)
mathjax-wrapper, v0.1.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.5 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
pdf-view, v0.50.0 (active)
permanent-delete, v0.1.5 (inactive)
tabasco, v0.5.0 (active)
tabs-to-spaces, v1.0.2 (inactive)
wordcount, v2.7.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by morassman** [comment]
Hi @lierdakil 

It shouldn't be necessary to use this package anymore. Atom now has the ability to drag and dock tabs built in. It was only before Atom 1.1 that tabasco had to be used. It's better to rather uninstall tabasco if you're using the latest version of Atom.

**Comment by lierdakil** [comment]
Good to know, thanks!
