### ISSUE TITLE
Failed to activate the tabasco package

### ISSUE THREAD

**Issue by rickydazla** [morassman/tabasco#9]
1. Install Tabasco

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [tabasco](https://github.com/morassman/tabasco) package 0.5.0

### Stack Trace

Failed to activate the tabasco package

```
At tabBarView.addEventListener is not a function

TypeError: tabBarView.addEventListener is not a function
    at Object.tabBarViewAdded (/packages/tabasco/lib/tabasco.coffee:112:16)
    at Object.connectPaneWithTabBarView (/packages/tabasco/lib/tabasco.coffee:80:10)
    at Object.paneAdded (/packages/tabasco/lib/tabasco.coffee:51:10)
    at /packages/tabasco/lib/tabasco.coffee:36:65
    at PaneContainer.module.exports.PaneContainer.observePanes (/app.asar/src/pane-container.js:90:9)
    at Workspace.module.exports.Workspace.observePanes (/app.asar/src/workspace.js:371:33)
    at Object.tabsActivated (/packages/tabasco/lib/tabasco.coffee:36:41)
    at Object.activate (/packages/tabasco/lib/tabasco.coffee:20:8)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -1:00.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:16.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
.bin undefined 
atom-beautify 0.29.17 
atom-color-highlight 3.0.9 
atom-liquid-snippets 0.3.0 
Atom-Syntax-highlighting-for-Sass 0.5.0 
atom-typescript 10.1.15 
atomic-chrome 0.3.0 
autoclose-html 0.23.0 
browser-plus 0.0.87 
busy-signal 1.3.0 
clipboard-history 0.6.6 
clipboard-plus 0.5.1 
dracula-theme 2.0.0 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.0.17 
git-control 0.8.2 
git-history 3.2.0 
git-log 0.4.1 
git-time-machine 1.5.6 
highlight-line 0.12.0 
intentions 1.1.2 
language-liquid 0.5.1 
linter 2.1.0 
linter-ui-default 1.1.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
monokai 0.22.0 
open-in-browser 0.4.7 
open-terminal-here 2.3.0 
pigments 0.39.0 
platformio-ide-terminal 2.5.0 
rainbow-windows 0.3.0 
tabasco 0.5.0 
terminal-panel 1.14.1 
terminal-plus 0.14.5 
```

**Comment by morassman** [comment]
Hi @rickydazla 

Since version 1.1 Atom has built-in support for dragging tabs, so you don't need to install Tabasco anymore. Since you're using version 1.15 you can just uninstall Tabasco and make use of Atom's own functionality.
